services:
  # === Nginx (Laravel 전용, 4000 포트) ===
  nginx:
    image: nginx:1.27-alpine
    container_name: blog-nginx
    ports:
      - "4000:80"                  # ← http://localhost:4000
    depends_on:
      - php
    volumes:
      - ../blog.backend:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - blognet

  # === PHP-FPM (Laravel) ===
  php:
    build:
      context: ./php
    container_name: blog-php
    environment:
      APP_ENV: local             # 개발환경일 때만 migrate 실행됨
    volumes:
      - ../blog.backend:/var/www/html:cached
      - ${MY_BACKEND_ENV_FILE:-./../blog.backend/.env}:/var/www/html/.env:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blognet

  # === Node (Next.js Dev Server, 3000 포트) ===
  node:
    build:
      context: ../blog.frontend
      dockerfile: ../blog.docker/node/Dockerfile
    container_name: blog-node
    working_dir: /usr/src/app
    command: sh -lc "yarn install && yarn dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_API_BASE=http://localhost:4000
    volumes:
      - ../blog.frontend:/usr/src/app:cached
      - ${MY_FRONTEND_ENV_FILE:-./../blog.frontend/.env}:/usr/src/app/.env:ro
    ports:
      - "3000:3000"
    networks:
      - blognet

  # === MariaDB ===
  db:
    image: mariadb:11
    container_name: blog-mariadb
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: blog
      MARIADB_PASSWORD: blogpass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - blognet
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p\"$${MARIADB_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 3s
      retries: 12

networks:
  blognet:
    driver: bridge

volumes:
  dbdata:
